Document: ascend-tfplugin
Title: Debian ascend-tfplugin Manual
Author: <insert document author here>
Abstract: This manual describes what ascend-tfplugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ascend-tfplugin/ascend-tfplugin.sgml.gz

Format: postscript
Files: /usr/share/doc/ascend-tfplugin/ascend-tfplugin.ps.gz

Format: text
Files: /usr/share/doc/ascend-tfplugin/ascend-tfplugin.text.gz

Format: HTML
Index: /usr/share/doc/ascend-tfplugin/html/index.html
Files: /usr/share/doc/ascend-tfplugin/html/*.html
