Document: ascend-cann-toolbox
Title: Debian ascend-cann-toolbox Manual
Author: <insert document author here>
Abstract: This manual describes what ascend-cann-toolbox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ascend-cann-toolbox/ascend-cann-toolbox.sgml.gz

Format: postscript
Files: /usr/share/doc/ascend-cann-toolbox/ascend-cann-toolbox.ps.gz

Format: text
Files: /usr/share/doc/ascend-cann-toolbox/ascend-cann-toolbox.text.gz

Format: HTML
Index: /usr/share/doc/ascend-cann-toolbox/html/index.html
Files: /usr/share/doc/ascend-cann-toolbox/html/*.html
