Document: ascend-tensorflow
Title: Debian ascend-tensorflow Manual
Author: <insert document author here>
Abstract: This manual describes what ascend-tensorflow is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ascend-tensorflow/ascend-tensorflow.sgml.gz

Format: postscript
Files: /usr/share/doc/ascend-tensorflow/ascend-tensorflow.ps.gz

Format: text
Files: /usr/share/doc/ascend-tensorflow/ascend-tensorflow.text.gz

Format: HTML
Index: /usr/share/doc/ascend-tensorflow/html/index.html
Files: /usr/share/doc/ascend-tensorflow/html/*.html
