Document: ascend-cann-toolkit
Title: Debian ascend-cann-toolkit Manual
Author: <insert document author here>
Abstract: This manual describes what ascend-cann-toolkit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ascend-cann-toolkit/ascend-cann-toolkit.sgml.gz

Format: postscript
Files: /usr/share/doc/ascend-cann-toolkit/ascend-cann-toolkit.ps.gz

Format: text
Files: /usr/share/doc/ascend-cann-toolkit/ascend-cann-toolkit.text.gz

Format: HTML
Index: /usr/share/doc/ascend-cann-toolkit/html/index.html
Files: /usr/share/doc/ascend-cann-toolkit/html/*.html
