Document: ascend-python3.7-numpy
Title: Debian ascend-python3.7-numpy Manual
Author: <insert document author here>
Abstract: This manual describes what ascend-python3.7-numpy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ascend-python3.7-numpy/ascend-python3.7-numpy.sgml.gz

Format: postscript
Files: /usr/share/doc/ascend-python3.7-numpy/ascend-python3.7-numpy.ps.gz

Format: text
Files: /usr/share/doc/ascend-python3.7-numpy/ascend-python3.7-numpy.text.gz

Format: HTML
Index: /usr/share/doc/ascend-python3.7-numpy/html/index.html
Files: /usr/share/doc/ascend-python3.7-numpy/html/*.html
