Document: ascend-mindspore
Title: Debian ascend-mindspore Manual
Author: <insert document author here>
Abstract: This manual describes what ascend-mindspore is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ascend-mindspore/ascend-mindspore.sgml.gz

Format: postscript
Files: /usr/share/doc/ascend-mindspore/ascend-mindspore.ps.gz

Format: text
Files: /usr/share/doc/ascend-mindspore/ascend-mindspore.text.gz

Format: HTML
Index: /usr/share/doc/ascend-mindspore/html/index.html
Files: /usr/share/doc/ascend-mindspore/html/*.html
