Document: ascend-cann-nnrt
Title: Debian ascend-cann-nnrt Manual
Author: <insert document author here>
Abstract: This manual describes what ascend-cann-nnrt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ascend-cann-nnrt/ascend-cann-nnrt.sgml.gz

Format: postscript
Files: /usr/share/doc/ascend-cann-nnrt/ascend-cann-nnrt.ps.gz

Format: text
Files: /usr/share/doc/ascend-cann-nnrt/ascend-cann-nnrt.text.gz

Format: HTML
Index: /usr/share/doc/ascend-cann-nnrt/html/index.html
Files: /usr/share/doc/ascend-cann-nnrt/html/*.html
