Document: ascend-cann-nnae
Title: Debian ascend-cann-nnae Manual
Author: <insert document author here>
Abstract: This manual describes what ascend-cann-nnae is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ascend-cann-nnae/ascend-cann-nnae.sgml.gz

Format: postscript
Files: /usr/share/doc/ascend-cann-nnae/ascend-cann-nnae.ps.gz

Format: text
Files: /usr/share/doc/ascend-cann-nnae/ascend-cann-nnae.text.gz

Format: HTML
Index: /usr/share/doc/ascend-cann-nnae/html/index.html
Files: /usr/share/doc/ascend-cann-nnae/html/*.html
