Document: ascend-npu
Title: Debian ascend-npu Manual
Author: <insert document author here>
Abstract: This manual describes what ascend-npu is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ascend-npu/ascend-npu.sgml.gz

Format: postscript
Files: /usr/share/doc/ascend-npu/ascend-npu.ps.gz

Format: text
Files: /usr/share/doc/ascend-npu/ascend-npu.text.gz

Format: HTML
Index: /usr/share/doc/ascend-npu/html/index.html
Files: /usr/share/doc/ascend-npu/html/*.html
