Document: ascend-torch
Title: Debian ascend-torch Manual
Author: <insert document author here>
Abstract: This manual describes what ascend-torch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ascend-torch/ascend-torch.sgml.gz

Format: postscript
Files: /usr/share/doc/ascend-torch/ascend-torch.ps.gz

Format: text
Files: /usr/share/doc/ascend-torch/ascend-torch.text.gz

Format: HTML
Index: /usr/share/doc/ascend-torch/html/index.html
Files: /usr/share/doc/ascend-torch/html/*.html
